import 'package:alluwalacademyadmin/features/shift_management/enums/shift_enums.dart';
import 'package:alluwalacademyadmin/features/shift_management/models/teaching_shift.dart';
import 'package:alluwalacademyadmin/features/shift_management/widgets/teacher_shift_calendar.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:syncfusion_flutter_calendar/calendar.dart';

void main() {
  final shift = TeachingShift(
    id: 'calendar-test-shift',
    teacherId: 'teacher-1',
    teacherName: 'Teacher One',
    studentIds: const ['student-1'],
    studentNames: const ['Student One'],
    shiftStart: DateTime(2026, 7, 14, 9),
    shiftEnd: DateTime(2026, 7, 14, 10),
    adminTimezone: 'America/New_York',
    teacherTimezone: 'America/New_York',
    subject: IslamicSubject.quranStudies,
    autoGeneratedName: 'Teacher One - Quran Studies',
    hourlyRate: 20,
    status: ShiftStatus.scheduled,
    createdByAdminId: 'admin-1',
    createdAt: DateTime(2026, 7, 1),
  );

  Future<void> pumpCalendar(
    WidgetTester tester, {
    required CalendarView initialView,
    ValueChanged<TeachingShift>? onSelectShift,
  }) {
    return tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: SizedBox(
            width: 1200,
            height: 800,
            child: TeacherShiftCalendar(
              shifts: [shift],
              initialDisplayDate: shift.shiftStart,
              initialView: initialView,
              onSelectShift: onSelectShift,
            ),
          ),
        ),
      ),
    );
  }

  testWidgets('renders and opens an appointment from the selectable grid',
      (tester) async {
    TeachingShift? selectedShift;
    await pumpCalendar(
      tester,
      initialView: CalendarView.week,
      onSelectShift: (shift) => selectedShift = shift,
    );

    await tester.tap(find.text('Grid'));
    await tester.pumpAndSettle();

    expect(find.text('Student One'), findsOneWidget);
    await tester.tap(find.text('Student One'));
    await tester.pump();

    expect(selectedShift?.id, shift.id);
  });

  testWidgets('renders appointments in the selectable month grid',
      (tester) async {
    await pumpCalendar(tester, initialView: CalendarView.month);
    await tester.pumpAndSettle();

    expect(find.textContaining('Student One'), findsOneWidget);
  });
}
