const admin = require('firebase-admin');
const fs = require('fs');

// Initialize admin with local ADC or service account if needed
// For now, let's try to use the default app
if (admin.apps.length === 0) {
    admin.initializeApp({
        projectId: 'alluwal-academy'
    });
}

const db = admin.firestore();

async function createTestShift() {
    const email = 'Mamasdiallo26@gmail.com';
    console.log(`🔍 Searching for teacher: ${email}`);

    const usersSnapshot = await db.collection('users')
        .where('e-mail', '==', email.toLowerCase())
        .limit(1)
        .get();

    if (usersSnapshot.empty) {
        console.error('❌ Teacher not found!');
        return;
    }

    const teacherDoc = usersSnapshot.docs[0];
    const teacherId = teacherDoc.id;
    const teacherName = teacherDoc.data().full_name || 'Test Teacher';

    console.log(`✅ Found teacher: ${teacherName} (${teacherId})`);

    const now = new Date();
    const shiftId = `test_hybrid_${Date.now()}`;

    const shiftData = {
        teacherId: teacherId,
        teacherName: teacherName,
        studentIds: ['student_1', 'student_2'],
        studentNames: ['Test Student 1', 'Test Student 2'],
        shiftStart: admin.firestore.Timestamp.fromDate(new Date(now.getTime() - 5 * 60000)),
        shiftEnd: admin.firestore.Timestamp.fromDate(new Date(now.getTime() + 60 * 60000)),
        status: 'scheduled',
        subject: 'Quran',
        autoGeneratedName: 'Hybrid Test Shift',
        hourlyRate: 20.0,
        createdByAdminId: 'admin_manual',
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
        adminTimezone: 'America/New_York',
        teacherTimezone: 'America/New_York',
        category: 'teaching',
        // Zoom Hub Fields
        hubMeetingId: '88390891438',
        breakoutRoomName: 'Room A',
        zoomRoutingMode: 'hybrid',
        zoomMeetingId: '88390891438',
        zoomMeetingCreatedAt: admin.firestore.FieldValue.serverTimestamp(),
    };

    console.log(`🚀 Creating test shift: ${shiftId}`);
    await db.collection('teaching_shifts').doc(shiftId).set(shiftData);

    console.log('\n' + '='.repeat(40));
    console.log('🎉 TEST SHIFT CREATED SUCCESSFULLY');
    console.log(`Shift ID: ${shiftId}`);
    console.log(`Teacher: ${email}`);
    console.log('Time: Active Now');
    console.log('='.repeat(40));
}

createTestShift().catch(console.error);
