import 'package:alluwalacademyadmin/features/shift_management/enums/shift_enums.dart';
import 'package:alluwalacademyadmin/features/shift_management/models/teaching_shift.dart';
import 'package:alluwalacademyadmin/features/time_clock/services/shift_timesheet_service.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('ShiftTimesheetService clock status helpers', () {
    TeachingShift shift({
      ShiftCategory category = ShiftCategory.leadership,
      DateTime? start,
      DateTime? end,
    }) {
      final shiftStart = start ?? DateTime(2026, 7, 9, 9);
      final shiftEnd = end ?? DateTime(2026, 7, 9, 10);
      return TeachingShift(
        id: 'leader-shift',
        teacherId: 'leader-1',
        teacherName: 'Leader One',
        studentIds: const [],
        studentNames: const [],
        shiftStart: shiftStart,
        shiftEnd: shiftEnd,
        adminTimezone: 'America/New_York',
        teacherTimezone: 'America/New_York',
        subject: IslamicSubject.other,
        autoGeneratedName: 'Operations duty',
        hourlyRate: 30,
        status: ShiftStatus.scheduled,
        createdByAdminId: 'admin-1',
        createdAt: DateTime(2026, 7, 1),
        category: category,
        leaderRole: 'operations',
      );
    }

    test('treats clock-out within five minutes of shift end as on time', () {
      final duty = shift();

      expect(
        ShiftTimesheetService.clockOutStatusForShift(
          duty,
          at: DateTime(2026, 7, 9, 9, 55),
        ),
        'on_time',
      );
      expect(
        ShiftTimesheetService.clockOutStatusForShift(
          duty,
          at: DateTime(2026, 7, 9, 10, 5),
        ),
        'on_time',
      );
      expect(
        ShiftTimesheetService.requiresClockOutNote(
          duty,
          at: DateTime(2026, 7, 9, 10, 5),
        ),
        isFalse,
      );
    });

    test('requires a note for early or late clock-out outside tolerance', () {
      final duty = shift();

      expect(
        ShiftTimesheetService.clockOutStatusForShift(
          duty,
          at: DateTime(2026, 7, 9, 9, 54),
        ),
        'early',
      );
      expect(
        ShiftTimesheetService.clockOutDeviationMinutes(
          duty,
          at: DateTime(2026, 7, 9, 9, 54),
        ),
        -6,
      );
      expect(
        ShiftTimesheetService.requiresClockOutNote(
          duty,
          at: DateTime(2026, 7, 9, 9, 54),
        ),
        isTrue,
      );

      expect(
        ShiftTimesheetService.clockOutStatusForShift(
          duty,
          at: DateTime(2026, 7, 9, 10, 6),
        ),
        'late',
      );
      expect(
        ShiftTimesheetService.clockOutDeviationMinutes(
          duty,
          at: DateTime(2026, 7, 9, 10, 6),
        ),
        6,
      );
      expect(
        ShiftTimesheetService.requiresClockOutNote(
          duty,
          at: DateTime(2026, 7, 9, 10, 6),
        ),
        isTrue,
      );
    });

    test('uses leadership display names instead of empty student labels', () {
      final duty = shift();
      final teaching = shift(category: ShiftCategory.teaching);

      expect(ShiftTimesheetService.workLabelForShift(duty), 'Operations duty');
      expect(
          ShiftTimesheetService.workLabelForShift(teaching), 'Operations duty');
    });
  });
}
