"use client";

import { onAuthStateChanged, type User } from "firebase/auth";
import { addDoc, collection, deleteDoc, doc, getDocs, query, serverTimestamp, Timestamp, updateDoc, where } from "firebase/firestore";
import { deleteObject, getDownloadURL, ref, uploadBytes } from "firebase/storage";
import { AlertTriangle, CalendarDays, Download, Edit3, FileText, Menu, MoreVertical, Paperclip, Plus, RefreshCw, Search, Shuffle, Trash2, Users, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { TeacherAccessPrompt, TeacherShell, openTeacherMobileMenu } from "@/components/TeacherDashboardHome";
import { auth, db, storage } from "@/lib/firebase";
import { getCurrentUserRecord, isCurrentUserTeacher } from "@/lib/userRoles";

type AccessState = "checking" | "signedOut" | "allowed" | "denied";
type Summary = { displayName: string; firstName: string; initials: string };
type Student = { id: string; name: string };
type Attachment = { name: string; originalName: string; size: number; url: string; downloadURL: string; type: string; storagePath: string; uploadedAt: string; uploadedBy: string };
type Assignment = { id: string; title: string; description: string; dueDate: Date | null; assignedTo: string[]; teacherId: string; teacherEmail: string; attachments: Attachment[]; status: string; createdAt: Date | null; updatedAt: Date | null };

export function TeacherAssignmentsPage() {
  const [access, setAccess] = useState<AccessState>("checking");
  const [user, setUser] = useState<User | null>(null);
  const [summary, setSummary] = useState<Summary>({ displayName: "Teacher", firstName: "Teacher", initials: "TE" });
  const [assignments, setAssignments] = useState<Assignment[]>([]);
  const [students, setStudents] = useState<Student[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [search, setSearch] = useState("");
  const [editing, setEditing] = useState<Assignment | "new" | null>(null);
  const [viewing, setViewing] = useState<Assignment | null>(null);
  const [deleting, setDeleting] = useState<Assignment | null>(null);

  useEffect(() => onAuthStateChanged(auth, async (nextUser) => {
    setUser(nextUser);
    if (!nextUser) { setAccess("signedOut"); setLoading(false); return; }
    const allowed = await isCurrentUserTeacher(nextUser);
    if (!allowed) { setAccess("denied"); setLoading(false); return; }
    const record = await getCurrentUserRecord(nextUser);
    setSummary(summaryFor(nextUser, record)); setAccess("allowed");
    await refreshAssignments(nextUser.uid, setAssignments, setStudents, setError, setLoading);
  }), []);

  const visible = useMemo(() => { const term = search.trim().toLowerCase(); return assignments.filter((item) => !term || [item.title, item.description, item.assignedTo.join(" ")].some((value) => value.toLowerCase().includes(term))); }, [assignments, search]);
  if (access !== "allowed") return <TeacherAccessPrompt access={access} />;

  const reload = async () => { if (user) await refreshAssignments(user.uid, setAssignments, setStudents, setError, setLoading); };
  return <TeacherShell activeLabel="Dashboard" breadcrumb="Overview / Assignments" summary={summary}><main className="min-h-full bg-[#F5F7FA] text-[#1E293B]"><MobileHeader summary={summary} /><section className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-extrabold">My Assignments</h1><p className="mt-1 text-sm text-[#64748B]">Create and manage work assigned to your students.</p></div><div className="flex gap-2"><button type="button" aria-label="Refresh assignments" onClick={() => void reload()} disabled={loading} className="grid h-11 w-11 place-items-center rounded-xl border border-[#CBD5E1] bg-white text-[#0386FF] disabled:opacity-50"><RefreshCw size={18} className={loading ? "animate-spin" : ""} /></button><button type="button" onClick={() => setEditing("new")} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#0386FF] px-4 font-bold text-white"><Plus size={18} />Create Assignment</button></div></div>
    <label className="relative mt-5 block"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#94A3B8]" size={19} /><input aria-label="Search assignments" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search assignments or students" className="h-11 w-full rounded-xl border border-[#CBD5E1] bg-white pl-10 pr-3" /></label>
    {error ? <div role="alert" className="mt-4 flex gap-3 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800"><AlertTriangle size={20} /><div className="flex-1"><p className="font-bold">Could not load assignments</p><p className="text-sm">{error}</p></div><button type="button" onClick={() => void reload()} className="font-bold">Retry</button></div> : null}{notice ? <p role="status" className={`mt-4 rounded-xl p-3 text-sm font-bold ${/success|deleted/i.test(notice) ? "bg-emerald-50 text-emerald-800" : "bg-red-50 text-red-800"}`}>{notice}</p> : null}
    {loading ? <div className="grid min-h-72 place-items-center"><RefreshCw className="animate-spin text-[#0386FF]" /></div> : visible.length ? <div className="mt-5 grid gap-4 md:grid-cols-2">{visible.map((item) => <AssignmentCard key={item.id} item={item} onView={() => setViewing(item)} onEdit={() => setEditing(item)} onDelete={() => setDeleting(item)} />)}</div> : <div className="mt-5 grid min-h-72 place-items-center rounded-3xl border border-dashed border-[#CBD5E1] bg-white p-8 text-center"><div><FileText size={60} className="mx-auto text-[#CBD5E1]" /><h2 className="mt-4 text-lg font-extrabold">{search ? "No assignments match your search" : "No assignments yet"}</h2><p className="mt-2 text-sm text-[#64748B]">Create an assignment and select at least one student.</p>{!search ? <button type="button" onClick={() => setEditing("new")} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#0386FF] px-4 font-bold text-white"><Plus size={18} />Create Assignment</button> : null}</div></div>}
  </section>{editing && user ? <AssignmentEditor assignment={editing === "new" ? null : editing} students={students} user={user} onClose={() => setEditing(null)} onSaved={async (message) => { setEditing(null); setNotice(message); await reload(); }} /> : null}{viewing ? <AssignmentDetails item={viewing} onClose={() => setViewing(null)} /> : null}{deleting && user ? <DeleteAssignment item={deleting} onClose={() => setDeleting(null)} onDeleted={async (message) => { setDeleting(null); setNotice(message); await reload(); }} /> : null}</main></TeacherShell>;
}

function MobileHeader({ summary }: { summary: Summary }) { return <header className="grid min-h-14 grid-cols-[56px_1fr_96px] items-center bg-white px-4 lg:hidden"><button type="button" aria-label="Open teacher menu" onClick={openTeacherMobileMenu} className="grid h-11 w-11 place-items-center rounded-xl"><Menu size={24} /></button><div className="text-center font-bold">Alluwal Education Hub</div><div className="flex justify-end gap-2"><button type="button" aria-label="Open teacher account options" onClick={openTeacherMobileMenu} className="grid h-10 w-10 place-items-center rounded-xl"><Shuffle size={19} /></button><span className="grid h-9 w-9 place-items-center rounded-full bg-[#009688] text-xs font-black text-white">{summary.initials}</span></div></header>; }

function AssignmentCard({ item, onView, onEdit, onDelete }: { item: Assignment; onView: () => void; onEdit: () => void; onDelete: () => void }) { const overdue = Boolean(item.dueDate && item.dueDate < new Date()); return <article className="rounded-2xl border border-[#E2E8F0] bg-white p-5 shadow-sm"><button type="button" onClick={onView} className="w-full text-left"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#EEF2FF] text-[#6366F1]"><FileText size={21} /></span><div className="min-w-0 flex-1"><h2 className="truncate text-lg font-extrabold">{item.title}</h2><p className="mt-1 line-clamp-2 text-sm text-[#64748B]">{item.description || "No description"}</p></div></div><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-[#EFF6FF] px-3 py-1 text-[#1D4ED8]"><Users size={13} className="mr-1 inline" />{item.assignedTo.length} students</span>{item.dueDate ? <span className={`rounded-full px-3 py-1 ${overdue ? "bg-red-50 text-red-700" : "bg-[#F8FAFC] text-[#475569]"}`}><CalendarDays size={13} className="mr-1 inline" />{dueLabel(item.dueDate)}</span> : null}{item.attachments.length ? <span className="rounded-full bg-amber-50 px-3 py-1 text-amber-800"><Paperclip size={13} className="mr-1 inline" />{item.attachments.length}</span> : null}</div></button><div className="mt-4 flex justify-end gap-2 border-t border-[#F1F5F9] pt-3"><button type="button" aria-label={`Edit ${item.title}`} onClick={onEdit} className="grid h-10 w-10 place-items-center rounded-xl text-[#0386FF] hover:bg-[#EFF6FF]"><Edit3 size={18} /></button><button type="button" aria-label={`Delete ${item.title}`} onClick={onDelete} className="grid h-10 w-10 place-items-center rounded-xl text-red-600 hover:bg-red-50"><Trash2 size={18} /></button></div></article>; }

function AssignmentEditor({ assignment, students, user, onClose, onSaved }: { assignment: Assignment | null; students: Student[]; user: User; onClose: () => void; onSaved: (message: string) => void }) { const [title, setTitle] = useState(assignment?.title ?? ""); const [description, setDescription] = useState(assignment?.description ?? ""); const [dueDate, setDueDate] = useState(assignment?.dueDate ? dateInput(assignment.dueDate) : ""); const [selected, setSelected] = useState(new Set(assignment?.assignedTo ?? [])); const [attachments, setAttachments] = useState<Attachment[]>(assignment?.attachments ?? []); const [busy, setBusy] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState(""); const pendingDocId = useRef(assignment?.id ?? doc(collection(db, "assignments")).id).current;
  const newPaths = useRef(new Set<string>()); const originalPaths = useRef(new Set((assignment?.attachments ?? []).map((file) => file.storagePath).filter(Boolean)));
  const cleanupNewUploads = async () => { await Promise.all(Array.from(newPaths.current).map((path) => deleteObject(ref(storage, path)).catch(() => null))); newPaths.current.clear(); };
  const cancel = async () => { if (busy || uploading) return; await cleanupNewUploads(); onClose(); };
  const upload = async (file: File) => { if (file.size >= 50 * 1024 * 1024) { setError("Files must be smaller than 50 MB."); return; } setUploading(true); setError(""); try { const unique = `${Date.now()}_${file.name.replace(/\s+/g, "_")}`; const storagePath = `assignment_files/${pendingDocId}/${unique}`; const storageRef = ref(storage, storagePath); await uploadBytes(storageRef, file, { contentType: file.type || undefined, customMetadata: { originalName: file.name, uploadedBy: user.uid, assignmentId: pendingDocId } }); const url = await getDownloadURL(storageRef); newPaths.current.add(storagePath); setAttachments((current) => [...current, { name: file.name, originalName: file.name, size: file.size, url, downloadURL: url, type: file.name.split(".").pop()?.toLowerCase() ?? "file", storagePath, uploadedAt: new Date().toISOString(), uploadedBy: user.uid }]); } catch (cause) { setError(actionError(cause, "Could not upload the file.")); } finally { setUploading(false); } };
  const removeAttachment = async (file: Attachment) => { setAttachments((current) => current.filter((item) => item.storagePath !== file.storagePath)); if (newPaths.current.has(file.storagePath)) { newPaths.current.delete(file.storagePath); await deleteObject(ref(storage, file.storagePath)).catch(() => null); } };
  const save = async () => { if (!title.trim()) { setError("Title is required."); return; } if (!selected.size) { setError("Please select at least one student."); return; } setBusy(true); setError(""); const payload = { title: title.trim(), description: description.trim(), due_date: dueDate ? Timestamp.fromDate(new Date(`${dueDate}T12:00:00`)) : null, assigned_to: Array.from(selected), teacher_id: user.uid, teacher_email: user.email, attachments, status: "active", type: "assignment", updated_at: serverTimestamp() }; try { if (assignment) await updateDoc(doc(db, "assignments", assignment.id), payload); else await addDoc(collection(db, "assignments"), { ...payload, created_at: serverTimestamp() }); const retained = new Set(attachments.map((file) => file.storagePath)); await Promise.all(Array.from(originalPaths.current).filter((path) => !retained.has(path)).map((path) => deleteObject(ref(storage, path)).catch(() => null))); newPaths.current.clear(); onSaved(assignment ? "Assignment updated successfully." : "Assignment created successfully."); } catch (cause) { setError(actionError(cause, "Could not save the assignment.")); } finally { setBusy(false); } };
  return <Modal label={assignment ? "Edit assignment" : "Create assignment"} onClose={() => void cancel()}><div className="space-y-4"><label className="block text-sm font-bold">Title<input aria-label="Assignment title" value={title} onChange={(event) => setTitle(event.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#CBD5E1] px-3 font-normal" /></label><label className="block text-sm font-bold">Description<textarea aria-label="Assignment description" value={description} onChange={(event) => setDescription(event.target.value)} rows={4} className="mt-1 w-full rounded-xl border border-[#CBD5E1] p-3 font-normal" /></label><label className="block text-sm font-bold">Due date<input aria-label="Assignment due date" type="date" value={dueDate} min={dateInput(new Date())} onChange={(event) => setDueDate(event.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#CBD5E1] px-3 font-normal" /></label><fieldset><legend className="text-sm font-bold">Students</legend><div className="mt-2 max-h-44 space-y-1 overflow-y-auto rounded-xl border border-[#E2E8F0] p-2">{students.length ? students.map((student) => <label key={student.id} className="flex min-h-10 cursor-pointer items-center gap-3 rounded-lg px-2 hover:bg-[#F8FAFC]"><input type="checkbox" checked={selected.has(student.name)} onChange={(event) => setSelected((current) => { const next = new Set(current); if (event.target.checked) next.add(student.name); else next.delete(student.name); return next; })} />{student.name}</label>) : <p className="p-3 text-sm text-[#64748B]">No students are available.</p>}</div></fieldset><label className="inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-xl border border-[#CBD5E1] px-4 font-bold text-[#0386FF]"><Paperclip size={18} />{uploading ? "Uploading…" : "Add File"}<input aria-label="Add assignment file" type="file" disabled={uploading} className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); event.target.value = ""; }} /></label>{attachments.map((file) => <div key={file.storagePath} className="flex items-center gap-2 rounded-xl bg-[#F8FAFC] p-3 text-sm"><FileText size={17} /><span className="min-w-0 flex-1 truncate">{file.name}</span><button type="button" aria-label={`Remove ${file.name}`} onClick={() => void removeAttachment(file)} className="text-red-600"><X size={17} /></button></div>)}{error ? <p role="alert" className="text-sm font-bold text-red-700">{error}</p> : null}<div className="grid grid-cols-2 gap-3"><button type="button" onClick={() => void cancel()} className="min-h-11 rounded-xl border border-[#CBD5E1] font-bold">Cancel</button><button type="button" disabled={busy || uploading} onClick={() => void save()} className="min-h-11 rounded-xl bg-[#0386FF] font-bold text-white disabled:opacity-50">{busy ? "Saving…" : assignment ? "Update Assignment" : "Create Assignment"}</button></div></div></Modal>; }

function AssignmentDetails({ item, onClose }: { item: Assignment; onClose: () => void }) { return <Modal label={`${item.title} details`} onClose={onClose}><h2 className="text-xl font-extrabold">{item.title}</h2>{item.description ? <p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#475569]">{item.description}</p> : null}<div className="mt-5 space-y-2 text-sm"><p><strong>Due:</strong> {item.dueDate ? dueLabel(item.dueDate) : "No due date"}</p><p><strong>Assigned to:</strong> {item.assignedTo.join(", ") || "No students"}</p></div>{item.attachments.length ? <div className="mt-5"><h3 className="font-extrabold">Attachments</h3><div className="mt-2 space-y-2">{item.attachments.map((file) => validHttp(file.url || file.downloadURL) ? <a key={file.storagePath || file.name} href={file.url || file.downloadURL} target="_blank" rel="noreferrer" className="flex min-h-11 items-center gap-3 rounded-xl border border-[#E2E8F0] px-3 text-sm font-bold text-[#0386FF]"><Download size={17} />{file.name}</a> : <p key={file.storagePath || file.name} className="rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{file.name}: This file was not uploaded to online storage.</p>)}</div></div> : null}</Modal>; }

function DeleteAssignment({ item, onClose, onDeleted }: { item: Assignment; onClose: () => void; onDeleted: (message: string) => void }) { const [busy, setBusy] = useState(false); const [error, setError] = useState(""); return <Modal label={`Delete ${item.title}`} onClose={onClose}><h2 className="text-xl font-extrabold">Delete Assignment?</h2><p className="mt-3 text-sm text-[#64748B]">This permanently deletes “{item.title}” and attempts to remove its uploaded files.</p>{error ? <p role="alert" className="mt-3 text-sm font-bold text-red-700">{error}</p> : null}<div className="mt-5 grid grid-cols-2 gap-3"><button type="button" onClick={onClose} className="min-h-11 rounded-xl border border-[#CBD5E1] font-bold">Cancel</button><button type="button" disabled={busy} onClick={async () => { setBusy(true); try { await deleteDoc(doc(db, "assignments", item.id)); const cleanup = await Promise.allSettled(item.attachments.filter((file) => file.storagePath).map((file) => deleteObject(ref(storage, file.storagePath)))); const failed = cleanup.filter((result) => result.status === "rejected").length; onDeleted(failed ? `Assignment deleted, but ${failed} uploaded file${failed === 1 ? "" : "s"} could not be removed.` : "Assignment deleted successfully."); } catch (cause) { setError(actionError(cause, "Could not delete the assignment.")); setBusy(false); } }} className="min-h-11 rounded-xl bg-red-600 font-bold text-white disabled:opacity-50">{busy ? "Deleting…" : "Delete"}</button></div></Modal>; }

function Modal({ label, onClose, children }: { label: string; onClose: () => void; children: React.ReactNode }) { return <section className="fixed inset-0 z-[100] grid items-end bg-black/45 sm:place-items-center" role="dialog" aria-modal="true" aria-label={label}><div className="max-h-[88vh] w-full overflow-y-auto rounded-t-3xl bg-white p-5 shadow-2xl sm:max-w-xl sm:rounded-3xl sm:p-6"><div className="mb-4 flex justify-end"><button type="button" aria-label="Close" onClick={onClose} className="grid h-10 w-10 place-items-center rounded-xl text-[#64748B] hover:bg-[#F8FAFC]"><X size={20} /></button></div>{children}</div></section>; }

async function refreshAssignments(uid: string, setAssignments: (items: Assignment[]) => void, setStudents: (items: Student[]) => void, setError: (value: string) => void, setLoading: (value: boolean) => void) { setLoading(true); setError(""); try { const [assignmentSnap, studentSnap] = await Promise.all([getDocs(query(collection(db, "assignments"), where("teacher_id", "==", uid))), getDocs(query(collection(db, "users"), where("user_type", "==", "student")))]); setAssignments(assignmentSnap.docs.map((item) => normalizeAssignment(item.id, item.data() as Record<string, unknown>)).sort((a, b) => (b.createdAt?.getTime() ?? 0) - (a.createdAt?.getTime() ?? 0))); setStudents(studentSnap.docs.map((item) => ({ id: item.id, name: displayName(item.data() as Record<string, unknown>) })).sort((a, b) => a.name.localeCompare(b.name))); } catch (cause) { setError(actionError(cause, "Could not load assignments.")); } finally { setLoading(false); } }
function normalizeAssignment(id: string, data: Record<string, unknown>): Assignment { return { id, title: stringValue(data.title) || "Untitled Assignment", description: stringValue(data.description), dueDate: dateValue(data.due_date ?? data.dueDate), assignedTo: stringArray(data.assigned_to ?? data.assignedTo), teacherId: stringValue(data.teacher_id ?? data.teacherId), teacherEmail: stringValue(data.teacher_email ?? data.teacherEmail), attachments: Array.isArray(data.attachments) ? data.attachments.map((value) => normalizeAttachment(value)).filter((value): value is Attachment => Boolean(value)) : [], status: stringValue(data.status) || "active", createdAt: dateValue(data.created_at ?? data.createdAt), updatedAt: dateValue(data.updated_at ?? data.updatedAt) }; }
function normalizeAttachment(value: unknown): Attachment | null { if (!value || typeof value !== "object") return null; const data = value as Record<string, unknown>; const name = stringValue(data.name ?? data.originalName) || "Attachment"; return { name, originalName: stringValue(data.originalName) || name, size: numberValue(data.size), url: stringValue(data.url ?? data.downloadURL), downloadURL: stringValue(data.downloadURL ?? data.url), type: stringValue(data.type), storagePath: stringValue(data.storagePath), uploadedAt: stringValue(data.uploadedAt), uploadedBy: stringValue(data.uploadedBy) }; }
function summaryFor(user: User, record: Record<string, unknown> | null): Summary { const name = record ? [stringValue(record.first_name), stringValue(record.last_name)].filter(Boolean).join(" ") : ""; const displayNameValue = name || user.displayName || user.email || "Teacher"; const words = displayNameValue.split(/\s+/); return { displayName: displayNameValue, firstName: words[0] || "Teacher", initials: words.slice(0, 2).map((word) => word[0]).join("").toUpperCase() || "TE" }; }
function displayName(data: Record<string, unknown>) { return [stringValue(data.first_name), stringValue(data.last_name)].filter(Boolean).join(" ") || stringValue(data.name ?? data.displayName) || "Unknown"; }
function stringValue(value: unknown) { return typeof value === "string" ? value.trim() : ""; } function stringArray(value: unknown) { return Array.isArray(value) ? value.map((item) => String(item ?? "").trim()).filter(Boolean) : []; } function numberValue(value: unknown) { const result = Number(value); return Number.isFinite(result) ? result : 0; }
function dateValue(value: unknown): Date | null { if (value instanceof Timestamp) return value.toDate(); if (value instanceof Date) return value; if (value && typeof value === "object" && "toDate" in value && typeof value.toDate === "function") return value.toDate(); if (typeof value === "string" || typeof value === "number") { const result = new Date(value); return Number.isNaN(result.getTime()) ? null : result; } return null; }
function dateInput(value: Date) { return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; } function dueLabel(value: Date) { const diff = Math.ceil((new Date(value.getFullYear(), value.getMonth(), value.getDate()).getTime() - new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate()).getTime()) / 86_400_000); return diff < 0 ? `Overdue (${Math.abs(diff)} day${Math.abs(diff) === 1 ? "" : "s"})` : diff === 0 ? "Today" : diff === 1 ? "Tomorrow" : new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(value); }
function validHttp(value: string) { try { const url = new URL(value); return url.protocol === "https:" || url.protocol === "http:"; } catch { return false; } } function actionError(cause: unknown, fallback: string) { const message = cause instanceof Error ? cause.message : ""; return /permission|denied/i.test(message) ? `${fallback} You do not have permission.` : /offline|network|unavailable/i.test(message) ? `${fallback} Check your connection and try again.` : `${fallback}${message ? ` ${message}` : ""}`; }
