// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi_iLhoVPezrUJTTu2az67Y1Pv31IsuP4',
    appId: '1:554077757249:web:07c7609546547fd6cc8bc0',
    messagingSenderId: '554077757249',
    projectId: 'alluwal-academy',
    authDomain: 'alluwal-academy.firebaseapp.com',
    storageBucket: 'alluwal-academy.firebasestorage.app',
    measurementId: 'G-F6605YZC8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ-JHKPs_VQTc8cDfb94h-uYvFPB8vjRM',
    appId: '1:554077757249:android:5a5c76e677152c4fcc8bc0',
    messagingSenderId: '554077757249',
    projectId: 'alluwal-academy',
    storageBucket: 'alluwal-academy.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtXZ9gUJ56KFB1QVvwAPdQnXnIr2hH7ig',
    appId: '1:554077757249:ios:3ffdd64aeab91d75cc8bc0',
    messagingSenderId: '554077757249',
    projectId: 'alluwal-academy',
    storageBucket: 'alluwal-academy.firebasestorage.app',
    iosBundleId: 'com.example.alluwalacademyadmin',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtXZ9gUJ56KFB1QVvwAPdQnXnIr2hH7ig',
    appId: '1:554077757249:ios:3ffdd64aeab91d75cc8bc0',
    messagingSenderId: '554077757249',
    projectId: 'alluwal-academy',
    storageBucket: 'alluwal-academy.firebasestorage.app',
    iosBundleId: 'com.example.alluwalacademyadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi_iLhoVPezrUJTTu2az67Y1Pv31IsuP4',
    appId: '1:554077757249:web:c4e201bf8ef8505fcc8bc0',
    messagingSenderId: '554077757249',
    projectId: 'alluwal-academy',
    authDomain: 'alluwal-academy.firebaseapp.com',
    storageBucket: 'alluwal-academy.firebasestorage.app',
    measurementId: 'G-77FD31KXXD',
  );

}