// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZY9R0tkIPpfpQqgh6mlb6h1xcmngbWYc',
    appId: '1:633115721273:web:0a9a1aef6591aebe6e17e8',
    messagingSenderId: '633115721273',
    projectId: 'alluwalacademy-e32c1',
    authDomain: 'alluwalacademy-e32c1.firebaseapp.com',
    storageBucket: 'alluwalacademy-e32c1.appspot.com',
    measurementId: 'G-LCN05KJ48P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTpl2IwUOVJsNJOt_H9af4Xt5-GhqYy5Q',
    appId: '1:633115721273:android:5d1d3ccc3df8f4776e17e8',
    messagingSenderId: '633115721273',
    projectId: 'alluwalacademy-e32c1',
    storageBucket: 'alluwalacademy-e32c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBkQZ-jRxLF6fWMAHocM8vxgosGOoXVpc',
    appId: '1:633115721273:ios:af997482b084ef606e17e8',
    messagingSenderId: '633115721273',
    projectId: 'alluwalacademy-e32c1',
    storageBucket: 'alluwalacademy-e32c1.appspot.com',
    iosBundleId: 'com.example.alluwalacademyadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBkQZ-jRxLF6fWMAHocM8vxgosGOoXVpc',
    appId: '1:633115721273:ios:02985af84438314c6e17e8',
    messagingSenderId: '633115721273',
    projectId: 'alluwalacademy-e32c1',
    storageBucket: 'alluwalacademy-e32c1.appspot.com',
    iosBundleId: 'com.example.alluwalacademyadmin.RunnerTests',
  );
}
