import 'package:flutter_test/flutter_test.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:alluwalacademyadmin/core/models/teaching_shift.dart';
import 'package:alluwalacademyadmin/core/enums/shift_enums.dart';

void main() {
  group('TeachingShift Platform Tracking', () {
    late TeachingShift testShift;

    setUp(() {
      testShift = TeachingShift(
        id: 'test-shift-1',
        teacherId: 'teacher-123',
        teacherName: 'John Doe',
        studentIds: ['student-1', 'student-2'],
        studentNames: ['Alice', 'Bob'],
        shiftStart: DateTime(2025, 11, 10, 9, 0),
        shiftEnd: DateTime(2025, 11, 10, 10, 0),
        adminTimezone: 'America/New_York',
        teacherTimezone: 'America/New_York',
        subject: IslamicSubject.quranStudies,
        autoGeneratedName: 'John Doe - Quran Studies',
        hourlyRate: 25.0,
        status: ShiftStatus.scheduled,
        createdByAdminId: 'admin-123',
        createdAt: DateTime(2025, 11, 1),
      );
    });

    group('Constructor', () {
      test('should create shift without platform', () {
        expect(testShift.lastClockInPlatform, isNull);
      });

      test('should create shift with platform', () {
        final shift = TeachingShift(
          id: 'test-shift-2',
          teacherId: 'teacher-123',
          teacherName: 'John Doe',
          studentIds: ['student-1'],
          studentNames: ['Alice'],
          shiftStart: DateTime(2025, 11, 10, 9, 0),
          shiftEnd: DateTime(2025, 11, 10, 10, 0),
          adminTimezone: 'America/New_York',
          teacherTimezone: 'America/New_York',
          subject: IslamicSubject.quranStudies,
          autoGeneratedName: 'John Doe - Quran Studies',
          hourlyRate: 25.0,
          status: ShiftStatus.scheduled,
          createdByAdminId: 'admin-123',
          createdAt: DateTime(2025, 11, 1),
          lastClockInPlatform: 'web',
        );

        expect(shift.lastClockInPlatform, 'web');
      });

      test('should accept all valid platforms', () {
        final platforms = [
          'web',
          'android',
          'ios',
          'macos',
          'windows',
          'linux'
        ];

        for (final platform in platforms) {
          final shift = TeachingShift(
            id: 'test-shift-$platform',
            teacherId: 'teacher-123',
            teacherName: 'John Doe',
            studentIds: ['student-1'],
            studentNames: ['Alice'],
            shiftStart: DateTime(2025, 11, 10, 9, 0),
            shiftEnd: DateTime(2025, 11, 10, 10, 0),
            adminTimezone: 'America/New_York',
            teacherTimezone: 'America/New_York',
            subject: IslamicSubject.quranStudies,
            autoGeneratedName: 'John Doe - Quran Studies',
            hourlyRate: 25.0,
            status: ShiftStatus.scheduled,
            createdByAdminId: 'admin-123',
            createdAt: DateTime(2025, 11, 1),
            lastClockInPlatform: platform,
          );

          expect(shift.lastClockInPlatform, platform);
        }
      });
    });

    group('copyWith', () {
      test('should copy shift without changing platform', () {
        final original = testShift.copyWith(lastClockInPlatform: 'android');
        final copied = original.copyWith(teacherName: 'Jane Doe');

        expect(copied.lastClockInPlatform, 'android');
        expect(copied.teacherName, 'Jane Doe');
      });

      test('should update platform using copyWith', () {
        final updated = testShift.copyWith(lastClockInPlatform: 'ios');

        expect(updated.lastClockInPlatform, 'ios');
        expect(testShift.lastClockInPlatform, isNull); // Original unchanged
      });

      test('should change platform from one to another', () {
        final withWeb = testShift.copyWith(lastClockInPlatform: 'web');
        expect(withWeb.lastClockInPlatform, 'web');

        final withAndroid = withWeb.copyWith(lastClockInPlatform: 'android');
        expect(withAndroid.lastClockInPlatform, 'android');
      });

      test('should preserve platform when copying other fields', () {
        final withPlatform = testShift.copyWith(lastClockInPlatform: 'web');
        final updated = withPlatform.copyWith(
          status: ShiftStatus.active,
          clockInTime: DateTime.now(),
        );

        expect(updated.lastClockInPlatform, 'web');
        expect(updated.status, ShiftStatus.active);
      });

      test('should copy telemetry fields', () {
        final activatedAt = DateTime.utc(2025, 11, 10, 15, 0);
        final updated = testShift.copyWith(
          activatedAt: activatedAt,
          autoClockOut: true,
          autoClockOutReason: 'System auto clock-out',
          completionState: 'partial',
          workedMinutes: 42,
        );

        expect(updated.activatedAt, activatedAt);
        expect(updated.autoClockOut, isTrue);
        expect(updated.autoClockOutReason, 'System auto clock-out');
        expect(updated.completionState, 'partial');
        expect(updated.workedMinutes, 42);
      });
    });

    group('toFirestore', () {
      test('should include platform in Firestore data', () {
        final shift = testShift.copyWith(lastClockInPlatform: 'web');
        final data = shift.toFirestore();

        expect(data['last_clock_in_platform'], 'web');
      });

      test('should include null platform in Firestore data', () {
        final data = testShift.toFirestore();

        expect(data.containsKey('last_clock_in_platform'), isTrue);
        expect(data['last_clock_in_platform'], isNull);
      });

      test('should serialize different platforms correctly', () {
        final platforms = ['web', 'android', 'ios'];

        for (final platform in platforms) {
          final shift = testShift.copyWith(lastClockInPlatform: platform);
          final data = shift.toFirestore();

          expect(data['last_clock_in_platform'], platform);
        }
      });

      test('should include all required fields along with platform', () {
        final shift = testShift.copyWith(lastClockInPlatform: 'android');
        final data = shift.toFirestore();

        // Verify core fields are still present
        expect(data['id'], shift.id);
        expect(data['teacher_id'], shift.teacherId);
        expect(data['teacher_name'], shift.teacherName);
        expect(data['status'], shift.status.name);
        expect(data['last_clock_in_platform'], 'android');
      });

      test('should serialize telemetry fields', () {
        final activatedAt = DateTime.utc(2025, 11, 10, 15, 0);
        final shift = testShift.copyWith(
          activatedAt: activatedAt,
          autoClockOut: true,
          autoClockOutReason: 'Auto',
          completionState: 'partial',
          workedMinutes: 30,
        );
        final data = shift.toFirestore();

        expect(data['activated_at'], Timestamp.fromDate(activatedAt));
        expect(data['auto_clock_out'], isTrue);
        expect(data['auto_clock_out_reason'], 'Auto');
        expect(data['completion_state'], 'partial');
        expect(data['worked_minutes'], 30);
      });
    });

    group('fromFirestore', () {
      test('should parse platform from Firestore document', () {
        final docData = {
          'id': 'test-shift-1',
          'teacher_id': 'teacher-123',
          'teacher_name': 'John Doe',
          'student_ids': ['student-1'],
          'student_names': ['Alice'],
          'shift_start': Timestamp.fromDate(DateTime(2025, 11, 10, 9, 0)),
          'shift_end': Timestamp.fromDate(DateTime(2025, 11, 10, 10, 0)),
          'admin_timezone': 'America/New_York',
          'teacher_timezone': 'America/New_York',
          'subject': 'quranStudies',
          'auto_generated_name': 'Test Shift',
          'hourly_rate': 25.0,
          'status': 'scheduled',
          'created_by_admin_id': 'admin-123',
          'created_at': Timestamp.fromDate(DateTime(2025, 11, 1)),
          'last_clock_in_platform': 'web',
        };

        // Note: We can't fully test fromFirestore without a mock DocumentSnapshot
        // This is a data structure validation test
        expect(docData['last_clock_in_platform'], 'web');
      });

      test('should handle missing platform field gracefully', () {
        final docData = {
          'id': 'test-shift-1',
          'teacher_id': 'teacher-123',
          'teacher_name': 'John Doe',
          'student_ids': ['student-1'],
          'student_names': ['Alice'],
          'shift_start': Timestamp.fromDate(DateTime(2025, 11, 10, 9, 0)),
          'shift_end': Timestamp.fromDate(DateTime(2025, 11, 10, 10, 0)),
          'admin_timezone': 'America/New_York',
          'teacher_timezone': 'America/New_York',
          'subject': 'quranStudies',
          'auto_generated_name': 'Test Shift',
          'hourly_rate': 25.0,
          'status': 'scheduled',
          'created_by_admin_id': 'admin-123',
          'created_at': Timestamp.fromDate(DateTime(2025, 11, 1)),
          // No last_clock_in_platform field
        };

        // Verify the field can be missing
        expect(docData.containsKey('last_clock_in_platform'), isFalse);
      });
    });

    group('Round-trip serialization', () {
      test('should preserve platform through serialize-deserialize cycle', () {
        final original = testShift.copyWith(lastClockInPlatform: 'ios');
        final serialized = original.toFirestore();

        // Verify platform is in serialized form
        expect(serialized['last_clock_in_platform'], 'ios');
      });

      test('should preserve null platform through serialize-deserialize cycle',
          () {
        final serialized = testShift.toFirestore();

        // Verify null platform is handled
        expect(serialized['last_clock_in_platform'], isNull);
      });

      test('should handle empty string platform', () {
        final shift = testShift.copyWith(lastClockInPlatform: '');
        final serialized = shift.toFirestore();

        expect(serialized['last_clock_in_platform'], '');
      });
    });

    group('Integration scenarios', () {
      test('should track platform change across multiple clock-ins', () {
        // First clock-in from web
        var shift = testShift.copyWith(
          lastClockInPlatform: 'web',
          status: ShiftStatus.active,
          clockInTime: DateTime.now(),
        );
        expect(shift.lastClockInPlatform, 'web');

        // Clock out
        shift = shift.copyWith(
          status: ShiftStatus.completed,
          clockOutTime: DateTime.now(),
        );
        expect(shift.lastClockInPlatform, 'web'); // Platform preserved

        // Next clock-in from mobile
        shift = shift.copyWith(
          lastClockInPlatform: 'android',
          status: ShiftStatus.active,
        );
        expect(shift.lastClockInPlatform, 'android');
      });

      test('should maintain platform during status changes', () {
        final shift = testShift.copyWith(lastClockInPlatform: 'ios');

        final active = shift.copyWith(status: ShiftStatus.active);
        expect(active.lastClockInPlatform, 'ios');

        final completed = active.copyWith(status: ShiftStatus.completed);
        expect(completed.lastClockInPlatform, 'ios');

        final cancelled = completed.copyWith(status: ShiftStatus.cancelled);
        expect(cancelled.lastClockInPlatform, 'ios');
      });

      test('should allow platform to be set during active shift', () {
        var shift = testShift.copyWith(status: ShiftStatus.active);
        expect(shift.lastClockInPlatform, isNull);

        shift = shift.copyWith(lastClockInPlatform: 'web');
        expect(shift.lastClockInPlatform, 'web');
        expect(shift.status, ShiftStatus.active);
      });
    });
  });

  group('TeachingShift Missed Shift Logic', () {
    late TeachingShift baseShift;

    setUp(() {
      baseShift = TeachingShift(
        id: 'missed-shift-1',
        teacherId: 'teacher-123',
        teacherName: 'John Doe',
        studentIds: ['student-1'],
        studentNames: ['Alice'],
        shiftStart: DateTime.utc(2025, 11, 10, 15, 0),
        shiftEnd: DateTime.utc(2025, 11, 10, 16, 0),
        adminTimezone: 'America/New_York',
        teacherTimezone: 'America/New_York',
        subject: IslamicSubject.quranStudies,
        autoGeneratedName: 'John Doe - Quran Studies',
        hourlyRate: 25.0,
        status: ShiftStatus.scheduled,
        createdByAdminId: 'admin-123',
        createdAt: DateTime(2025, 11, 1),
      );
    });

    test('clockInGraceDeadline returns shift end (UTC)', () {
      expect(baseShift.clockInGraceDeadline(), baseShift.shiftEnd.toUtc());
    });

    test('clockInGraceDeadline ignores next shift start time', () {
      final nextShiftStartUtc = DateTime.utc(2025, 11, 10, 16, 5);
      final deadline =
          baseShift.clockInGraceDeadline(nextShiftStartUtc: nextShiftStartUtc);

      expect(deadline, baseShift.shiftEnd.toUtc());
    });

    test('clockInGraceDeadline returns shift end when next shift is immediate',
        () {
      final nextShiftStartUtc = DateTime.utc(2025, 11, 10, 16, 0);
      final deadline =
          baseShift.clockInGraceDeadline(nextShiftStartUtc: nextShiftStartUtc);

      expect(deadline, DateTime.utc(2025, 11, 10, 16, 0));
    });

    test('shouldBeMarkedAsMissed is false before shift starts', () {
      final futureShift = baseShift.copyWith(
        shiftStart: DateTime.utc(2025, 11, 10, 18, 0),
        shiftEnd: DateTime.utc(2025, 11, 10, 19, 0),
      );

      expect(
        futureShift.shouldBeMarkedAsMissed(
          nowUtcOverride: DateTime.utc(2025, 11, 10, 17, 0),
        ),
        isFalse,
      );
    });

    test('shouldBeMarkedAsMissed is false before grace window ends', () {
      expect(
        baseShift.shouldBeMarkedAsMissed(
          nowUtcOverride: DateTime.utc(2025, 11, 10, 16, 10),
        ),
        isFalse,
      );
    });

    test('shouldBeMarkedAsMissed is false (handled by backend)', () {
      expect(
        baseShift.shouldBeMarkedAsMissed(
          nowUtcOverride: DateTime.utc(2025, 11, 10, 16, 16),
        ),
        isFalse,
      );
    });

    test(
        'shouldBeMarkedAsMissed is false even when next shift exists (handled by backend)',
        () {
      final nextShiftStartUtc = DateTime.utc(2025, 11, 10, 16, 5);

      expect(
        baseShift.shouldBeMarkedAsMissed(
          nowUtcOverride: DateTime.utc(2025, 11, 10, 16, 4),
          nextShiftStartUtc: nextShiftStartUtc,
        ),
        isFalse,
      );

      expect(
        baseShift.shouldBeMarkedAsMissed(
          nowUtcOverride: DateTime.utc(2025, 11, 10, 16, 6),
          nextShiftStartUtc: nextShiftStartUtc,
        ),
        isFalse,
      );
    });

    test('shouldBeMarkedAsMissed immediate when next shift starts immediately',
        () {
      expect(
        baseShift.shouldBeMarkedAsMissed(
          nowUtcOverride: DateTime.utc(2025, 11, 10, 16, 0, 30),
          nextShiftStartUtc: DateTime.utc(2025, 11, 10, 16, 0),
        ),
        isFalse,
      );
    });

    test('shouldBeMarkedAsMissed is false when teacher already clocked in', () {
      final shiftWithClockIn = baseShift.copyWith(
        clockInTime: DateTime.utc(2025, 11, 10, 15, 5),
      );

      expect(
        shiftWithClockIn.shouldBeMarkedAsMissed(
          nowUtcOverride: DateTime.utc(2025, 11, 10, 16, 30),
        ),
        isFalse,
      );
    });

    test('shouldBeMarkedAsMissed is false when status is not scheduled', () {
      final completedShift = baseShift.copyWith(
        status: ShiftStatus.completed,
      );

      expect(
        completedShift.shouldBeMarkedAsMissed(
          nowUtcOverride: DateTime.utc(2025, 11, 10, 16, 30),
        ),
        isFalse,
      );
    });
  });

  group('TeachingShift Completion Helpers', () {
    final base = TeachingShift(
      id: 'completion-1',
      teacherId: 'teacher-123',
      teacherName: 'John Doe',
      studentIds: const ['student-1'],
      studentNames: const ['Alice'],
      shiftStart: DateTime.utc(2025, 11, 10, 15, 0),
      shiftEnd: DateTime.utc(2025, 11, 10, 16, 0),
      adminTimezone: 'America/New_York',
      teacherTimezone: 'America/New_York',
      subject: IslamicSubject.quranStudies,
      autoGeneratedName: 'John Doe - Quran Studies',
      hourlyRate: 20.0,
      status: ShiftStatus.scheduled,
      createdByAdminId: 'admin-123',
      createdAt: DateTime.utc(2025, 10, 31),
    );

    test('scheduledDurationMinutes returns total minutes', () {
      expect(base.scheduledDurationMinutes, 60);
    });

    test('deriveCompletionStatus returns missed when no work', () {
      expect(base.deriveCompletionStatus(), ShiftStatus.missed);
    });

    test(
        'deriveCompletionStatus returns fully completed when worked >= scheduled',
        () {
      final worked = base.copyWith(workedMinutes: 60);
      expect(worked.deriveCompletionStatus(), ShiftStatus.fullyCompleted);
    });

    test(
        'deriveCompletionStatus returns partially completed when worked < scheduled',
        () {
      final worked = base.copyWith(workedMinutes: 20);
      expect(worked.deriveCompletionStatus(), ShiftStatus.partiallyCompleted);
    });

    test('workedRatio returns null when no work data', () {
      expect(base.workedRatio, isNull);
    });

    test('workedRatio returns ratio when data available', () {
      final worked = base.copyWith(workedMinutes: 30);
      expect(worked.workedRatio, closeTo(0.5, 0.0001));
    });
  });
}
