const admin = require('firebase-admin');
const { onCall, onRequest, HttpsError } = require('firebase-functions/v2/https');
const { getRealtimeKitConfig, isRealtimeKitConfigured } = require('../services/realtimekit/config');
const realtimeKit = require('../services/realtimekit/client');

const REALTIMEKIT_REQUIRED_SECRETS = [
  'CLOUDFLARE_ACCOUNT_ID',
  'REALTIMEKIT_APP_ID',
  'CLOUDFLARE_REALTIME_API_TOKEN',
];

const _normalizeUidList = (rawList) => {
  if (!Array.isArray(rawList)) return [];
  const seen = new Set();
  const result = [];
  for (const item of rawList) {
    if (typeof item !== 'string') continue;
    const value = item.trim();
    if (!value || seen.has(value)) continue;
    seen.add(value);
    result.push(value);
  }
  return result;
};

const _toDate = (raw) => {
  if (!raw) return null;
  if (raw.toDate) return raw.toDate();
  const date = new Date(raw);
  return Number.isFinite(date.getTime()) ? date : null;
};

const _deriveShiftDisplayName = (shiftData) => {
  if (!shiftData) return 'Class';
  const candidates = [
    shiftData.custom_name,
    shiftData.customName,
    shiftData.auto_generated_name,
    shiftData.autoGeneratedName,
    shiftData.shift_title,
    shiftData.shiftTitle,
    shiftData.subject_display_name,
    shiftData.subjectDisplayName,
  ];
  for (const candidate of candidates) {
    const value = String(candidate || '').trim();
    if (value) return value;
  }
  return 'Class';
};

const getUserDisplayName = async (uid, fallback = 'Participant') => {
  if (!uid) return fallback;
  try {
    const userDoc = await admin.firestore().collection('users').doc(uid).get();
    if (!userDoc.exists) return fallback;
    const data = userDoc.data() || {};
    const fullName = [data.first_name || data.firstName, data.last_name || data.lastName]
      .filter(Boolean)
      .join(' ')
      .trim();
    return fullName || data['e-mail'] || data.email || fallback;
  } catch (_) {
    return fallback;
  }
};

const _truthy = (value) => value === true || value === 'true' || value === 1 || value === '1';

const _roleList = (value) => {
  if (!Array.isArray(value)) return [];
  return value
    .map((role) => String(role || '').trim().toLowerCase())
    .filter(Boolean);
};

const _isAdminRole = (role) => (
  role === 'admin' ||
  role === 'super_admin' ||
  role === 'admin_teacher'
);

const getUserDataForCaller = async (uid, token = {}) => {
  if (!uid) return null;
  const db = admin.firestore();

  const userDoc = await db.collection('users').doc(uid).get();
  if (userDoc.exists) return userDoc.data() || {};

  const rawEmail = typeof token?.email === 'string' ? token.email.trim() : '';
  if (!rawEmail) return null;

  const lowerEmail = rawEmail.toLowerCase();
  const emailDoc = await db.collection('users').doc(lowerEmail).get();
  if (emailDoc.exists) return emailDoc.data() || {};

  if (rawEmail !== lowerEmail) {
    const originalEmailDoc = await db.collection('users').doc(rawEmail).get();
    if (originalEmailDoc.exists) return originalEmailDoc.data() || {};
  }

  for (const field of ['email', 'e-mail']) {
    const query = await db.collection('users')
      .where(field, '==', lowerEmail)
      .limit(1)
      .get();
    if (!query.empty) return query.docs[0].data() || {};
  }

  return null;
};

const isUserAdmin = async (uid, token = {}) => {
  if (!uid) return false;
  try {
    const tokenRole = String(token.role || token.user_type || token.userType || '').trim().toLowerCase();
    const tokenRoles = [
      ..._roleList(token.roles),
      ..._roleList(token.secondary_roles),
      ..._roleList(token.secondaryRoles),
    ];
    if (
      _isAdminRole(tokenRole) ||
      tokenRoles.some(_isAdminRole) ||
      _truthy(token.admin) ||
      _truthy(token.isAdmin) ||
      _truthy(token.is_admin) ||
      _truthy(token.is_super_admin) ||
      _truthy(token.isSuperAdmin) ||
      _truthy(token.is_admin_teacher) ||
      _truthy(token.isAdminTeacher)
    ) {
      return true;
    }

    const data = await getUserDataForCaller(uid, token);
    if (!data) return false;
    const role = String(data.role || '').trim().toLowerCase();
    const userType = String(data.user_type || data.userType || '').trim().toLowerCase();
    const secondaryRoles = [
      ..._roleList(data.roles),
      ..._roleList(data.secondary_roles),
      ..._roleList(data.secondaryRoles),
    ];
    return (
      _isAdminRole(role) ||
      _isAdminRole(userType) ||
      secondaryRoles.some(_isAdminRole) ||
      _truthy(data.is_admin) ||
      _truthy(data.isAdmin) ||
      _truthy(data.is_super_admin) ||
      _truthy(data.isSuperAdmin) ||
      _truthy(data.is_admin_teacher) ||
      _truthy(data.isAdminTeacher)
    );
  } catch (_) {
    return false;
  }
};

const getGuardianIdsForStudents = async (studentIds) => {
  const guardianIds = new Set();
  for (const studentId of _normalizeUidList(studentIds)) {
    const studentDoc = await admin.firestore().collection('users').doc(studentId).get();
    if (!studentDoc.exists) continue;
    const data = studentDoc.data() || {};
    for (const guardianId of _normalizeUidList([
      ...(Array.isArray(data.guardian_ids) ? data.guardian_ids : []),
      ...(Array.isArray(data.guardianIds) ? data.guardianIds : []),
    ])) {
      guardianIds.add(guardianId);
    }
  }
  return guardianIds;
};

const isUserParentOfStudent = async (uid, studentIds) => {
  if (!uid) return false;
  const guardianIds = await getGuardianIdsForStudents(studentIds);
  return guardianIds.has(uid);
};

const isStudentAccessSuspended = async (uid) => {
  if (!uid) return false;
  const userDoc = await admin.firestore().collection('users').doc(uid).get();
  if (!userDoc.exists) return false;
  const data = userDoc.data() || {};
  return data.access_suspended === true || data.accessSuspended === true;
};

const getRealtimeKitShiftOrThrow = async (shiftId) => {
  const shiftRef = admin.firestore().collection('teaching_shifts').doc(shiftId);
  const shiftDoc = await shiftRef.get();
  if (!shiftDoc.exists) throw new HttpsError('not-found', 'Shift not found');

  const shiftData = shiftDoc.data() || {};
  const teacherId = shiftData.teacher_id || shiftData.teacherId || '';
  const studentIds = _normalizeUidList(shiftData.student_ids || shiftData.studentIds || []);
  const meetingId = String(
    shiftData.realtimekit_meeting_id ||
    shiftData.realtimekitMeetingId ||
    '',
  ).trim();

  return { shiftRef, shiftData, teacherId, studentIds, meetingId };
};

const assertJoinWindowOrThrow = (shiftData) => {
  const shiftStart = _toDate(shiftData.shift_start || shiftData.shiftStart);
  const shiftEnd = _toDate(shiftData.shift_end || shiftData.shiftEnd);
  const nowMs = Date.now();
  const startMs = shiftStart?.getTime();
  const endMs = shiftEnd?.getTime();
  const allowedStartMs = Number.isFinite(startMs)
    ? startMs - 10 * 60 * 1000
    : nowMs - 10 * 60 * 1000;
  const allowedEndMs = Number.isFinite(endMs)
    ? endMs + 10 * 60 * 1000
    : nowMs + 2 * 60 * 60 * 1000;

  if (nowMs < allowedStartMs) {
    const minutesUntil = Math.ceil((allowedStartMs - nowMs) / 60000);
    throw new HttpsError(
      'failed-precondition',
      `You can join 10 minutes before the class starts. Please wait ${minutesUntil} minute(s).`,
    );
  }
  if (nowMs > allowedEndMs) {
    throw new HttpsError('failed-precondition', 'The class window has ended');
  }
  return {
    allowedStartIso: new Date(allowedStartMs).toISOString(),
    allowedEndIso: new Date(allowedEndMs).toISOString(),
  };
};

const getAccessForUser = async ({ uid, token, teacherId, studentIds }) => {
  const isTeacher = uid === teacherId;
  const isStudent = studentIds.includes(uid);
  const isAdmin = await isUserAdmin(uid, token);
  const isParent = !isTeacher && !isStudent && !isAdmin
    ? await isUserParentOfStudent(uid, studentIds)
    : false;

  if (!isTeacher && !isStudent && !isAdmin && !isParent) {
    throw new HttpsError('permission-denied', 'You are not allowed to join this class');
  }
  if (isStudent && await isStudentAccessSuspended(uid)) {
    throw new HttpsError(
      'permission-denied',
      'Class access is suspended because of an outstanding unpaid invoice.',
    );
  }
  if (isAdmin) return 'admin';
  if (isTeacher) return 'teacher';
  if (isParent) return 'parent';
  return 'student';
};

const ensureMeeting = async ({ shiftId, shiftRef, shiftData, meetingId }) => {
  if (meetingId) {
    try {
      await realtimeKit.getMeeting(meetingId);
      return meetingId;
    } catch (err) {
      console.warn('[RealtimeKit] Stored meeting lookup failed; creating a new one:', err.message);
    }
  }

  const shiftName = _deriveShiftDisplayName(shiftData);
  const response = await realtimeKit.createMeeting({
    title: shiftName,
    persist_chat: true,
    session_keep_alive_time_in_secs: 600,
  });
  const nextMeetingId = response?.data?.id;
  if (!nextMeetingId) throw new Error('RealtimeKit did not return a meeting ID');

  await shiftRef.set({
    realtimekit_meeting_id: nextMeetingId,
    realtimekit_meeting_title: shiftName,
    realtimekit_provider: 'cloudflare_realtimekit',
    realtimekit_created_at: admin.firestore.FieldValue.serverTimestamp(),
    realtimekit_updated_at: admin.firestore.FieldValue.serverTimestamp(),
  }, { merge: true });

  return nextMeetingId;
};

const addParticipantForRole = async ({ meetingId, uid, displayName, role, recordingEnabled }) => {
  const config = getRealtimeKitConfig();
  const canRecordRole = role === 'teacher' || role === 'admin';
  const presetName = recordingEnabled && canRecordRole
    ? config.presets.teacherRecorder
    : config.presets[role] || config.presets.student;
  const participantsResponse = await realtimeKit.listMeetingParticipants(meetingId);
  const existingParticipant = (Array.isArray(participantsResponse?.data)
    ? participantsResponse.data
    : []).find((item) => item.custom_participant_id === uid);

  if (existingParticipant?.id) {
    if (existingParticipant.preset_name !== presetName) {
      await realtimeKit.updateParticipant(meetingId, existingParticipant.id, {
        preset_name: presetName,
        name: displayName,
      });
    }
    const tokenResponse = await realtimeKit.refreshParticipantToken(meetingId, existingParticipant.id);
    return {
      participantId: existingParticipant.id,
      token: tokenResponse?.data?.token || null,
      presetName,
    };
  }

  const response = await realtimeKit.addParticipant(meetingId, {
    custom_participant_id: uid,
    preset_name: presetName,
    name: displayName,
  });

  return {
    participantId: response?.data?.id || null,
    token: response?.data?.token || null,
    presetName,
  };
};

const syncTeacherRecordingPreset = async ({ meetingId, teacherId, recordingEnabled }) => {
  if (!meetingId || !teacherId) return false;
  const participantsResponse = await realtimeKit.listMeetingParticipants(meetingId);
  const participants = Array.isArray(participantsResponse?.data)
    ? participantsResponse.data
    : [];
  const teacherParticipant = participants.find((item) => item.custom_participant_id === teacherId);
  if (!teacherParticipant?.id) return false;

  const config = getRealtimeKitConfig();
  const presetName = recordingEnabled
    ? config.presets.teacherRecorder
    : config.presets.teacher;
  if (teacherParticipant.preset_name === presetName) return false;

  await realtimeKit.updateParticipant(meetingId, teacherParticipant.id, {
    preset_name: presetName,
  });
  return true;
};

const buildJoinResponse = async ({ shiftId, uid, token, displayName, role, guest = false }) => {
  if (!isRealtimeKitConfigured()) {
    throw new HttpsError('unavailable', 'RealtimeKit video is not configured');
  }

  const { shiftRef, shiftData, teacherId, studentIds, meetingId } =
    await getRealtimeKitShiftOrThrow(shiftId);
  const joinWindow = assertJoinWindowOrThrow(shiftData);

  if (!guest) {
    const resolvedRole = await getAccessForUser({ uid, token, teacherId, studentIds });
    role = resolvedRole;
  }

  if (shiftData.realtimekit_locked === true && ['student', 'parent', 'guest'].includes(role)) {
    throw new HttpsError('failed-precondition', 'This class is locked by the teacher.');
  }

  const recordingEnabled = shiftData.realtimekit_recording_enabled === true;
  const nextMeetingId = await ensureMeeting({ shiftId, shiftRef, shiftData, meetingId });
  const participant = await addParticipantForRole({
    meetingId: nextMeetingId,
    uid,
    displayName,
    role,
    recordingEnabled,
  });

  if (!participant.token) {
    throw new Error('RealtimeKit did not return a participant token');
  }

  await shiftRef.set({
    realtimekit_meeting_id: nextMeetingId,
    realtimekit_last_token_issued_at: admin.firestore.FieldValue.serverTimestamp(),
    realtimekit_updated_at: admin.firestore.FieldValue.serverTimestamp(),
  }, { merge: true });

  return {
    success: true,
    provider: 'realtimekit',
    authToken: participant.token,
    token: participant.token,
    meetingId: nextMeetingId,
    participantId: participant.participantId,
    presetName: participant.presetName,
    userRole: role,
    displayName,
    shiftName: _deriveShiftDisplayName(shiftData),
    roomLocked: shiftData.realtimekit_locked === true,
    recordingEnabled,
    joinWindow,
  };
};

const getRealtimeKitJoinToken = onCall({
  secrets: REALTIMEKIT_REQUIRED_SECRETS,
}, async (request) => {
  const uid = request.auth?.uid;
  const shiftId = request.data?.shiftId;
  if (!uid) throw new HttpsError('unauthenticated', 'Authentication required');
  if (!shiftId || typeof shiftId !== 'string') {
    throw new HttpsError('invalid-argument', 'Missing or invalid shiftId');
  }

  const displayName = await getUserDisplayName(uid);
  return buildJoinResponse({
    shiftId,
    uid,
    token: request.auth?.token,
    displayName,
    role: 'student',
  });
});

const getRealtimeKitGuestJoin = onRequest({
  cors: true,
  secrets: REALTIMEKIT_REQUIRED_SECRETS,
}, async (req, res) => {
  res.set('Cache-Control', 'no-store');
  if (req.method === 'OPTIONS') {
    res.status(204).send('');
    return;
  }

  try {
    const shiftId = req.query.shiftId || req.query.shift_id || req.body?.shiftId;
    if (!shiftId || typeof shiftId !== 'string') {
      res.status(400).json({ success: false, error: 'Missing or invalid shiftId' });
      return;
    }
    const rawName = req.query.name || req.body?.name;
    const displayName = String(rawName || 'Guest').trim().slice(0, 80) || 'Guest';
    const uid = `guest_${shiftId}_${Date.now()}`;
    const result = await buildJoinResponse({
      shiftId,
      uid,
      displayName,
      role: 'guest',
      guest: true,
    });
    res.status(200).json(result);
  } catch (err) {
    const status = err instanceof HttpsError ? 400 : 500;
    if (status >= 500) {
      console.error('[RealtimeKit] Guest join failed:', err);
    }
    res.status(status).json({
      success: false,
      error: err.message || 'Unable to join this class right now.',
    });
  }
});

const getRealtimeKitRoomPresence = onCall({
  secrets: REALTIMEKIT_REQUIRED_SECRETS,
}, async (request) => {
  const uid = request.auth?.uid;
  const shiftId = request.data?.shiftId;
  if (!uid) throw new HttpsError('unauthenticated', 'Authentication required');
  if (!shiftId || typeof shiftId !== 'string') {
    throw new HttpsError('invalid-argument', 'Missing or invalid shiftId');
  }

  const { shiftData, teacherId, studentIds, meetingId } =
    await getRealtimeKitShiftOrThrow(shiftId);
  await getAccessForUser({ uid, token: request.auth?.token, teacherId, studentIds });

  if (!meetingId) {
    return {
      success: true,
      roomName: null,
      meetingId: null,
      participantCount: 0,
      participants: [],
      inJoinWindow: true,
      generatedAtIso: new Date().toISOString(),
    };
  }

  const response = await realtimeKit.listMeetingParticipants(meetingId);
  const participants = Array.isArray(response?.data) ? response.data : [];
  return {
    success: true,
    roomName: meetingId,
    meetingId,
    participantCount: participants.length,
    participants: participants.map((participant) => ({
      identity: participant.custom_participant_id || participant.id || '',
      name: participant.name || participant.custom_participant_id || 'Participant',
      role: participant.preset_name || null,
      joinedAtIso: participant.created_at || null,
      isPublisher: true,
    })),
    inJoinWindow: true,
    generatedAtIso: new Date().toISOString(),
    shiftName: _deriveShiftDisplayName(shiftData),
  };
});

const setRealtimeKitRoomLock = onCall(async (request) => {
  const uid = request.auth?.uid;
  const shiftId = request.data?.shiftId;
  const locked = request.data?.locked === true;
  if (!uid) throw new HttpsError('unauthenticated', 'Authentication required');
  if (!shiftId || typeof shiftId !== 'string') {
    throw new HttpsError('invalid-argument', 'Missing or invalid shiftId');
  }

  const { shiftRef, teacherId } = await getRealtimeKitShiftOrThrow(shiftId);
  const isAdmin = await isUserAdmin(uid, request.auth?.token);
  if (uid !== teacherId && !isAdmin) {
    throw new HttpsError('permission-denied', 'Only teachers/admins can manage this class');
  }

  await shiftRef.set({
    realtimekit_locked: locked,
    realtimekit_updated_at: admin.firestore.FieldValue.serverTimestamp(),
  }, { merge: true });
  return { success: true, locked };
});

// Admin-only: allow or disallow recording for a single class. Teachers receive
// the recording-capable preset on their next join only while this is enabled.
const setRealtimeKitRecordingEnabled = onCall({
  secrets: REALTIMEKIT_REQUIRED_SECRETS,
}, async (request) => {
  const uid = request.auth?.uid;
  const shiftId = request.data?.shiftId;
  const enabled = request.data?.enabled === true;
  if (!uid) throw new HttpsError('unauthenticated', 'Authentication required');
  if (!shiftId || typeof shiftId !== 'string') {
    throw new HttpsError('invalid-argument', 'Missing or invalid shiftId');
  }

  const { shiftRef, teacherId, meetingId } = await getRealtimeKitShiftOrThrow(shiftId);
  if (!(await isUserAdmin(uid, request.auth?.token))) {
    throw new HttpsError('permission-denied', 'Only admins can change class recording settings');
  }

  await shiftRef.set({
    realtimekit_recording_enabled: enabled,
    realtimekit_updated_at: admin.firestore.FieldValue.serverTimestamp(),
  }, { merge: true });
  await syncTeacherRecordingPreset({
    meetingId,
    teacherId,
    recordingEnabled: enabled,
  }).catch(() => false);
  return { success: true, recordingEnabled: enabled };
});

const bulkSetRealtimeKitRecordingEnabled = onCall({
  secrets: REALTIMEKIT_REQUIRED_SECRETS,
}, async (request) => {
  const uid = request.auth?.uid;
  const rawShiftIds = request.data?.shiftIds;
  const enabled = request.data?.enabled === true;
  if (!uid) throw new HttpsError('unauthenticated', 'Authentication required');
  if (!Array.isArray(rawShiftIds)) {
    throw new HttpsError('invalid-argument', 'Missing or invalid shiftIds');
  }
  if (!(await isUserAdmin(uid, request.auth?.token))) {
    throw new HttpsError('permission-denied', 'Only admins can change class recording settings');
  }

  const shiftIds = _normalizeUidList(rawShiftIds).slice(0, 500);
  if (shiftIds.length === 0) {
    return { success: true, recordingEnabled: enabled, updatedCount: 0 };
  }

  const db = admin.firestore();
  const batch = db.batch();
  const presetSyncs = [];

  for (const shiftId of shiftIds) {
    const { shiftRef, teacherId, meetingId } = await getRealtimeKitShiftOrThrow(shiftId);
    batch.set(shiftRef, {
      realtimekit_recording_enabled: enabled,
      realtimekit_updated_at: admin.firestore.FieldValue.serverTimestamp(),
    }, { merge: true });
    if (meetingId) {
      presetSyncs.push(syncTeacherRecordingPreset({
        meetingId,
        teacherId,
        recordingEnabled: enabled,
      }).catch(() => false));
    }
  }

  await batch.commit();
  const syncedResults = await Promise.all(presetSyncs);
  return {
    success: true,
    recordingEnabled: enabled,
    updatedCount: shiftIds.length,
    activeParticipantsUpdated: syncedResults.filter(Boolean).length,
  };
});

const kickRealtimeKitParticipant = onCall({
  secrets: REALTIMEKIT_REQUIRED_SECRETS,
}, async (request) => {
  const uid = request.auth?.uid;
  const { shiftId, identity } = request.data || {};
  if (!uid) throw new HttpsError('unauthenticated', 'Authentication required');
  if (!shiftId || !identity) {
    throw new HttpsError('invalid-argument', 'Missing shiftId or identity');
  }

  const { teacherId, meetingId } = await getRealtimeKitShiftOrThrow(shiftId);
  const isAdmin = await isUserAdmin(uid, request.auth?.token);
  if (uid !== teacherId && !isAdmin) {
    throw new HttpsError('permission-denied', 'Only teachers/admins can manage this class');
  }
  if (!meetingId) return { success: true, removed: false };

  const response = await realtimeKit.listMeetingParticipants(meetingId);
  const participant = (Array.isArray(response?.data) ? response.data : [])
    .find((item) => item.custom_participant_id === identity || item.id === identity);
  if (!participant?.id && !identity) return { success: true, removed: false };
  await realtimeKit.kickActiveSessionParticipants(meetingId, {
    custom_participant_ids: [participant?.custom_participant_id || identity],
  });
  return { success: true, removed: true };
});

// Server-side mute is intentionally omitted: RealtimeKit has no mute API for
// this pass, and the in-room Cloudflare host controls cover muting.

module.exports = {
  getRealtimeKitJoinToken,
  getRealtimeKitGuestJoin,
  getRealtimeKitRoomPresence,
  kickRealtimeKitParticipant,
  setRealtimeKitRoomLock,
  setRealtimeKitRecordingEnabled,
  bulkSetRealtimeKitRecordingEnabled,
};
