import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:alluwalacademyadmin/firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  final email = 'Mamasdiallo26@gmail.com';
  print('🔍 Searching for teacher: $email');

  final users = await FirebaseFirestore.instance
      .collection('users')
      .where('e-mail', isEqualTo: email.toLowerCase())
      .get();

  if (users.docs.isEmpty) {
    print('❌ Teacher not found!');
    return;
  }

  final teacher = users.docs.first;
  final teacherId = teacher.id;
  final teacherName = teacher.data()['full_name'] ?? 'Test Teacher';

  print('✅ Found teacher: $teacherName ($teacherId)');

  final now = DateTime.now();
  final shiftId = 'test_hybrid_${now.millisecondsSinceEpoch}';

  final shiftData = {
    'teacherId': teacherId,
    'teacherName': teacherName,
    'studentIds': ['student_1', 'student_2'],
    'studentNames': ['Test Student 1', 'Test Student 2'],
    'shiftStart': Timestamp.fromDate(now.subtract(Duration(minutes: 5))),
    'shiftEnd': Timestamp.fromDate(now.add(Duration(hours: 1))),
    'status': 'scheduled',
    'subject': 'Quran',
    'autoGeneratedName': 'Hybrid Test Shift',
    'hourlyRate': 20.0,
    'createdByAdminId': 'admin_manual',
    'createdAt': FieldValue.serverTimestamp(),
    'adminTimezone': 'America/New_York',
    'teacherTimezone': 'America/New_York',
    'category': 'teaching',
    // Zoom Hub Fields
    'hubMeetingId':
        '88390891438', // Real meeting ID for testing if possible, or just a dummy
    'breakoutRoomName': 'Room A',
    'zoomRoutingMode': 'hybrid',
    // Pre-set some fake zoom info so the join button appears
    'zoomMeetingId': '88390891438',
    'zoomMeetingCreatedAt': FieldValue.serverTimestamp(),
  };

  print('🚀 Creating test shift: $shiftId');
  await FirebaseFirestore.instance
      .collection('teaching_shifts')
      .doc(shiftId)
      .set(shiftData);

  print('\n' + '=' * 40);
  print('🎉 TEST SHIFT CREATED SUCCESSFULLY');
  print('Shift ID: $shiftId');
  print('Teacher: $email');
  print('Time: Active Now');
  print('=' * 40);
  print('\nNEXT STEPS:');
  print('1. Log in to the Mobile App as $email');
  print('2. Find the shift "Hybrid Test Shift" in your schedule.');
  print('3. Tap "Join Class".');
  print('4. The app should fetch the Host Key and attempt to claim host.');
  print(
      '5. Check the logs for "Attempting to claim host with key" and "markBreakoutRoomsOpened".');
  print(
      '6. Refresh this document in Firestore to see if "breakout_rooms_opened_at" is set.');
  print('=' * 40);
}
