#!/usr/bin/env node
'use strict';

const admin = require('firebase-admin');

// Initialize Firebase Admin (assuming default credentials or similar setup to other scripts)
admin.initializeApp({ projectId: 'alluwal-academy' });
const db = admin.firestore();

async function analyzeShifts() {
  console.log('='.repeat(80));
  console.log('INVESTIGATING SHIFTS WITH "Class #tpl_tp" OR MISSING NAMES');
  console.log('='.repeat(80));
  
  // We will stream through all teaching shifts to avoid memory issues if the collection is large.
  // Alternatively, we can fetch all if it's not too big. Let's try to fetch all.
  console.log('Fetching all teaching_shifts...');
  const snapshot = await db.collection('teaching_shifts').get();
  console.log(`Found ${snapshot.docs.length} total shifts.`);

  const suspiciousShifts = [];
  const tplIdShifts = [];
  const missingNameShifts = [];
  
  for (const doc of snapshot.docs) {
    const data = doc.data();
    const id = doc.id;
    
    const hasTplTplId = id.startsWith('tpl_tpl_') || id.includes('tpl_tpl_') || (data.template_id && data.template_id.includes('tpl_tpl_'));
    const isMissingAutoGeneratedName = !data.auto_generated_name || data.auto_generated_name.trim() === '';
    const isMissingCustomName = !data.custom_name || data.custom_name.trim() === '';
    const isMissingNames = isMissingAutoGeneratedName && isMissingCustomName;
    
    if (hasTplTplId || isMissingNames) {
      const shiftInfo = {
        id,
        teacher_id: data.teacher_id,
        teacher_name: data.teacher_name,
        student_ids: data.student_ids,
        student_names: data.student_names,
        template_id: data.template_id,
        series_id: data.recurrence_series_id,
        shift_start: data.shift_start ? data.shift_start.toDate().toISOString() : null,
        created_at: data.created_at ? data.created_at.toDate().toISOString() : null,
        created_by: data.created_by,
        auto_generated_name: data.auto_generated_name,
        custom_name: data.custom_name,
        hasTplTplId,
        isMissingNames
      };
      
      suspiciousShifts.push(shiftInfo);
      
      if (hasTplTplId) tplIdShifts.push(shiftInfo);
      if (isMissingNames) missingNameShifts.push(shiftInfo);
    }
  }

  console.log(`\nFound ${suspiciousShifts.length} suspicious shifts total.`);
  console.log(`- ${tplIdShifts.length} have an ID or template ID with "tpl_tpl_"`);
  console.log(`- ${missingNameShifts.length} are missing both custom and auto_generated names`);

  console.log('\n--- Analysis of Suspicious Shifts ---');
  
  // Group by teacher
  const byTeacher = {};
  // Group by template_id
  const byTemplate = {};
  // Group by creation script / created_by (if available)
  const byCreatedBy = {};
  // Check student counts
  let missingStudentsCount = 0;
  
  for (const s of suspiciousShifts) {
    byTeacher[s.teacher_name || s.teacher_id || 'Unknown'] = (byTeacher[s.teacher_name || s.teacher_id || 'Unknown'] || 0) + 1;
    byTemplate[s.template_id || 'None'] = (byTemplate[s.template_id || 'None'] || 0) + 1;
    byCreatedBy[s.created_by || 'Unknown'] = (byCreatedBy[s.created_by || 'Unknown'] || 0) + 1;
    
    if (!s.student_ids || s.student_ids.length === 0) {
      missingStudentsCount++;
    }
  }

  console.log('\nBreakdown by Teacher:');
  Object.entries(byTeacher).sort((a,b) => b[1] - a[1]).forEach(([k, v]) => console.log(`  ${k}: ${v} shifts`));

  console.log('\nBreakdown by Template ID (Top 10):');
  Object.entries(byTemplate).sort((a,b) => b[1] - a[1]).slice(0, 10).forEach(([k, v]) => console.log(`  ${k}: ${v} shifts`));

  console.log('\nBreakdown by created_by:');
  Object.entries(byCreatedBy).sort((a,b) => b[1] - a[1]).forEach(([k, v]) => console.log(`  ${k}: ${v} shifts`));
  
  console.log(`\nShifts with NO students assigned: ${missingStudentsCount} out of ${suspiciousShifts.length}`);

  console.log('\n--- Sample of 5 shifts with "tpl_tpl_" in ID ---');
  console.dir(tplIdShifts.slice(0, 5), { depth: null });

  console.log('\n--- Sample of 5 shifts with missing names ---');
  console.dir(missingNameShifts.slice(0, 5), { depth: null });

}

analyzeShifts()
  .then(() => process.exit(0))
  .catch(e => {
    console.error('Error:', e);
    process.exit(1);
  });
