class SurahInfo {
  final int number;
  final String nameEn;
  final String nameAr;
  final int ayahCount;

  const SurahInfo(this.number, this.nameEn, this.nameAr, this.ayahCount);

  @override
  String toString() => '$number. $nameEn ($nameAr)';
}

const List<SurahInfo> allSurahs = [
  SurahInfo(1, 'Al-Fatiha', 'الفاتحة', 7),
  SurahInfo(2, 'Al-Baqarah', 'البقرة', 286),
  SurahInfo(3, 'Aal-E-Imran', 'آل عمران', 200),
  SurahInfo(4, 'An-Nisa', 'النساء', 176),
  SurahInfo(5, 'Al-Ma\'idah', 'المائدة', 120),
  SurahInfo(6, 'Al-An\'am', 'الأنعام', 165),
  SurahInfo(7, 'Al-A\'raf', 'الأعراف', 206),
  SurahInfo(8, 'Al-Anfal', 'الأنفال', 75),
  SurahInfo(9, 'At-Tawbah', 'التوبة', 129),
  SurahInfo(10, 'Yunus', 'يونس', 109),
  SurahInfo(11, 'Hud', 'هود', 123),
  SurahInfo(12, 'Yusuf', 'يوسف', 111),
  SurahInfo(13, 'Ar-Ra\'d', 'الرعد', 43),
  SurahInfo(14, 'Ibrahim', 'إبراهيم', 52),
  SurahInfo(15, 'Al-Hijr', 'الحجر', 99),
  SurahInfo(16, 'An-Nahl', 'النحل', 128),
  SurahInfo(17, 'Al-Isra', 'الإسراء', 111),
  SurahInfo(18, 'Al-Kahf', 'الكهف', 110),
  SurahInfo(19, 'Maryam', 'مريم', 98),
  SurahInfo(20, 'Taha', 'طه', 135),
  SurahInfo(21, 'Al-Anbiya', 'الأنبياء', 112),
  SurahInfo(22, 'Al-Hajj', 'الحج', 78),
  SurahInfo(23, 'Al-Mu\'minun', 'المؤمنون', 118),
  SurahInfo(24, 'An-Nur', 'النور', 64),
  SurahInfo(25, 'Al-Furqan', 'الفرقان', 77),
  SurahInfo(26, 'Ash-Shu\'ara', 'الشعراء', 227),
  SurahInfo(27, 'An-Naml', 'النمل', 93),
  SurahInfo(28, 'Al-Qasas', 'القصص', 88),
  SurahInfo(29, 'Al-Ankabut', 'العنكبوت', 69),
  SurahInfo(30, 'Ar-Rum', 'الروم', 60),
  SurahInfo(31, 'Luqman', 'لقمان', 34),
  SurahInfo(32, 'As-Sajdah', 'السجدة', 30),
  SurahInfo(33, 'Al-Ahzab', 'الأحزاب', 73),
  SurahInfo(34, 'Saba', 'سبأ', 54),
  SurahInfo(35, 'Fatir', 'فاطر', 45),
  SurahInfo(36, 'Ya-Sin', 'يس', 83),
  SurahInfo(37, 'As-Saffat', 'الصافات', 182),
  SurahInfo(38, 'Sad', 'ص', 88),
  SurahInfo(39, 'Az-Zumar', 'الزمر', 75),
  SurahInfo(40, 'Ghafir', 'غافر', 85),
  SurahInfo(41, 'Fussilat', 'فصلت', 54),
  SurahInfo(42, 'Ash-Shura', 'الشورى', 53),
  SurahInfo(43, 'Az-Zukhruf', 'الزخرف', 89),
  SurahInfo(44, 'Ad-Dukhan', 'الدخان', 59),
  SurahInfo(45, 'Al-Jathiyah', 'الجاثية', 37),
  SurahInfo(46, 'Al-Ahqaf', 'الأحقاف', 35),
  SurahInfo(47, 'Muhammad', 'محمد', 38),
  SurahInfo(48, 'Al-Fath', 'الفتح', 29),
  SurahInfo(49, 'Al-Hujurat', 'الحجرات', 18),
  SurahInfo(50, 'Qaf', 'ق', 45),
  SurahInfo(51, 'Adh-Dhariyat', 'الذاريات', 60),
  SurahInfo(52, 'At-Tur', 'الطور', 49),
  SurahInfo(53, 'An-Najm', 'النجم', 62),
  SurahInfo(54, 'Al-Qamar', 'القمر', 55),
  SurahInfo(55, 'Ar-Rahman', 'الرحمن', 78),
  SurahInfo(56, 'Al-Waqi\'ah', 'الواقعة', 96),
  SurahInfo(57, 'Al-Hadid', 'الحديد', 29),
  SurahInfo(58, 'Al-Mujadila', 'المجادلة', 22),
  SurahInfo(59, 'Al-Hashr', 'الحشر', 24),
  SurahInfo(60, 'Al-Mumtahanah', 'الممتحنة', 13),
  SurahInfo(61, 'As-Saff', 'الصف', 14),
  SurahInfo(62, 'Al-Jumu\'ah', 'الجمعة', 11),
  SurahInfo(63, 'Al-Munafiqun', 'المنافقون', 11),
  SurahInfo(64, 'At-Taghabun', 'التغابن', 18),
  SurahInfo(65, 'At-Talaq', 'الطلاق', 12),
  SurahInfo(66, 'At-Tahrim', 'التحريم', 12),
  SurahInfo(67, 'Al-Mulk', 'الملك', 30),
  SurahInfo(68, 'Al-Qalam', 'القلم', 52),
  SurahInfo(69, 'Al-Haqqah', 'الحاقة', 52),
  SurahInfo(70, 'Al-Ma\'arij', 'المعارج', 44),
  SurahInfo(71, 'Nuh', 'نوح', 28),
  SurahInfo(72, 'Al-Jinn', 'الجن', 28),
  SurahInfo(73, 'Al-Muzzammil', 'المزمل', 20),
  SurahInfo(74, 'Al-Muddathir', 'المدثر', 56),
  SurahInfo(75, 'Al-Qiyamah', 'القيامة', 40),
  SurahInfo(76, 'Al-Insan', 'الإنسان', 31),
  SurahInfo(77, 'Al-Mursalat', 'المرسلات', 50),
  SurahInfo(78, 'An-Naba', 'النبأ', 40),
  SurahInfo(79, 'An-Nazi\'at', 'النازعات', 46),
  SurahInfo(80, 'Abasa', 'عبس', 42),
  SurahInfo(81, 'At-Takwir', 'التكوير', 29),
  SurahInfo(82, 'Al-Infitar', 'الانفطار', 19),
  SurahInfo(83, 'Al-Mutaffifin', 'المطففين', 36),
  SurahInfo(84, 'Al-Inshiqaq', 'الانشقاق', 25),
  SurahInfo(85, 'Al-Buruj', 'البروج', 22),
  SurahInfo(86, 'At-Tariq', 'الطارق', 17),
  SurahInfo(87, 'Al-A\'la', 'الأعلى', 19),
  SurahInfo(88, 'Al-Ghashiyah', 'الغاشية', 26),
  SurahInfo(89, 'Al-Fajr', 'الفجر', 30),
  SurahInfo(90, 'Al-Balad', 'البلد', 20),
  SurahInfo(91, 'Ash-Shams', 'الشمس', 15),
  SurahInfo(92, 'Al-Layl', 'الليل', 21),
  SurahInfo(93, 'Ad-Duha', 'الضحى', 11),
  SurahInfo(94, 'Ash-Sharh', 'الشرح', 8),
  SurahInfo(95, 'At-Tin', 'التين', 8),
  SurahInfo(96, 'Al-Alaq', 'العلق', 19),
  SurahInfo(97, 'Al-Qadr', 'القدر', 5),
  SurahInfo(98, 'Al-Bayyinah', 'البينة', 8),
  SurahInfo(99, 'Az-Zalzalah', 'الزلزلة', 8),
  SurahInfo(100, 'Al-Adiyat', 'العاديات', 11),
  SurahInfo(101, 'Al-Qari\'ah', 'القارعة', 11),
  SurahInfo(102, 'At-Takathur', 'التكاثر', 8),
  SurahInfo(103, 'Al-Asr', 'العصر', 3),
  SurahInfo(104, 'Al-Humazah', 'الهمزة', 9),
  SurahInfo(105, 'Al-Fil', 'الفيل', 5),
  SurahInfo(106, 'Quraysh', 'قريش', 4),
  SurahInfo(107, 'Al-Ma\'un', 'الماعون', 7),
  SurahInfo(108, 'Al-Kawthar', 'الكوثر', 3),
  SurahInfo(109, 'Al-Kafirun', 'الكافرون', 6),
  SurahInfo(110, 'An-Nasr', 'النصر', 3),
  SurahInfo(111, 'Al-Masad', 'المسد', 5),
  SurahInfo(112, 'Al-Ikhlas', 'الإخلاص', 4),
  SurahInfo(113, 'Al-Falaq', 'الفلق', 5),
  SurahInfo(114, 'An-Nas', 'الناس', 6),
];

SurahInfo? getSurahByNumber(int number) {
  if (number < 1 || number > 114) return null;
  return allSurahs[number - 1];
}
